---
title: "regression_analysis_homework_2"
author: Chaorui Zhang
date: 2021/4/29
output:
  html_document: default
  word_document: default
  pdf_document:
    includes:
      in_header: header.tex
    keep_tex: yes
    latex_engine: xelatex
---

homework 2
=========
张朝瑞
-------
12020113002
---------
数量经济学
---------

对第三章练习4的程序
---------------
调用包
```{r}
library(pls)
library(corpcor)
```
对各个问题的函数
```{r}
significant_different_test <-function (data_lm,df_data){
    df_coef =summary(data_lm)$coef
    # length(df_coef[,1])
    for(i in seq(from = 2,to=length(df_coef[,1]))){
        if(df_coef[i,4]<0.001){
            print(sprintf('多元线性模型下,%s 十分显著',rownames(df_coef)[i]))
        }else if(df_coef[i,4]<0.01){
            print(sprintf('多元线性模型下,%s 中等显著',rownames(df_coef)[i]))
        }else if(df_coef[i,4]<0.05){
            print(sprintf('多元线性模型下,%s 比较显著',rownames(df_coef)[i]))
        }else if(df_coef[i,4]<0.1){
            print(sprintf('多元线性模型下,%s 有点显著',rownames(df_coef)[i]))
        }else{
            print(sprintf('多元线性模型下,%s 并不显著,p值为%f',rownames(df_coef)[i],df_coef[i,4]))
        }

    }
    print('方差分析表为')
    print(anova(data_lm))
}

coef_and_partial_coef <-function (df_data){
    df_coef = cor(df_data)
    df_partial_coef = cor2pcor(df_coef)
    for(i in seq(length(df_coef[1,]))){
        for(j in seq(from = i,to = length(df_coef[1,]))){
            print(sprintf('%s与%s的相关系数为%f,偏相关系数为%f',rownames(df_coef)[i],
                          rownames(df_coef)[j],df_coef[i,j],df_partial_coef[i,j]))
        }
    }

}
beta_minus_interval <-function(data_lm,beta_num_1,beta_num_2,alpha){
  coef = summary(data_lm)$coef
  
  #将b1和b2看为独立的正态分布
  if(alpha<0.5){
    print('置信区间的概率取值可能有问题')
  }
  len_interval = -2*qnorm(p=(1-alpha)/2,sd=sqrt(coef[(beta_num_1+1),2]**2+coef[(beta_num_2+1),2]**2))
  pre = coef[(beta_num_1+1),1]-coef[(beta_num_2+1),1]
  upper = pre+len_interval/2
  supper = pre - len_interval/2
  print(sprintf('b%d-b%d预测值为%f',beta_num_1,beta_num_2,pre))
  print(sprintf('b%d-b%d的%f的置信区间为[%f,%f]',beta_num_1,beta_num_2,alpha,supper,upper))
  return(data.frame(pre=pre,sup=supper,up=upper))
}

```
练习4
```{r}
ex_4<-function (){
    print('excersice 4')
    print('============')
    df_data = data.frame(y  = c(95,111,95,107,110,95,92,100,91,101),
                     x1 = c(6.21,6.29,6.38,6.5,6.52,6.55,6.61,6.77,6.82,6.96),
                     x2 =c(10.2,11.8,9.9,11.7,11.1,9.3,10.3,9.8,8.8,9.6))
    formula_multiple_linear = y~x1+x2
    data_lm = lm(formula = formula_multiple_linear,data = df_data)
    print('question 1')
    print('------------')
    significant_different_test(data_lm,df_data)
    print('------------')
    print('question 2')
    print('------------')
    print('我不会啊')
    print('------------')
    print('question 3')
    print('------------')
    print('相关系数与偏相关系数的比较')
    coef_and_partial_coef(df_data)
    print('分析')
    print('本题中,由于x1与x2有一定程度的负相关,因此影响了y与x1的相关系数')
    print('y与x1的偏相关系数是正的,但因为x1与x2的负相关,使得y与x1的相关系数是负数')
    print('------------')
    print('question 4')
    print('------------')
    x0 = data.frame(x1=9.3,x2=16.5)
    predict_x0 = predict(lm(formula_multiple_linear,df_data),x0,interval = 'prediction',level=0.95)
    predict_x0
    print(sprintf('y0的预测值为%f',predict_x0[1]))
    print(sprintf('y0的0.95预测区间为[%f,%f]',predict_x0[2],predict_x0[3]))
    print('------------')
    print('question 5')
    print('------------')
    beta_minus_interval(data_lm,1,2,0.95)
    print('------------')
}
```
运行
```{r}
ex_4()
```